# Generated by Django 4.2.2 on 2023-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="datecompleted",
            field=models.DateTimeField(null=True),
        ),
    ]
